"""add assistant

Revision ID: d69322653621
Revises: 95bd8de6aa22
Create Date: 2024-04-06 01:05:46.341290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69322653621'
down_revision: Union[str, None] = '95bd8de6aa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('file_ids', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.String(length=256), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('object', sa.String(length=256), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistants')
    # ### end Alembic commands ###
