name: nur

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - poetry
      - run
      - python
      - api/endpoint.py
    ports:
      - "8000:8000"
    volumes:
      - shared_content:/app/content
    environment:
      - NUR_API_HOST=web
      - NUR_API_PORT=8000

  slack:
    depends_on:
      - web
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - poetry
      - run
      - python
      - slack/bot.py
    volumes:
      - shared_content:/app/content
    environment:
      - NUR_API_HOST=web
      - NUR_API_PORT=8000

volumes:
  shared_content:
