toptal-apps:
  app:
    replicaCount: 1
    ports:
    - name: api
      number: &port 3020
      args: ['poetry', 'run', 'python', 'api/endpoint.py']
    
    - name: slack
      number: &port 3021
      args: ['poetry', 'run', 'python', 'slack/channel_interaction.py']

service:
  healthCheck: false
  type: ClusterIP
  port: *port

settings:
  environments:
    common:
      NUR_API_HOST: http://top-assist.toptal.rocks"
      NUR_API_PORT: *port

ingressRoute:
  host: top-assist.toptal.rocks
  oauth: false

tolerations: &tolerations
  - key: cloud.google.com_gke-preemptible
    operator: Exists

affinity: &affinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "cloud.google.com/gke-nodepool"
          operator: In
          values:
          - "preemptible"
